# chatbot/views.py
from django.http import JsonResponse
from django.shortcuts import render
import time

def index(request):
    return render(request, 'chatbot/index.html')

def execute_steps(request):
    messages = []
    
    # Step 1: Question rewrite
    messages.append('Step 1: Question rewrite is running...')
    time.sleep(2)  # Giả lập thời gian xử lý

    # Step 2: Question review
    messages.append('Step 2: Question review is running...')
    time.sleep(2)

    # Step 3: Final question generation
    messages.append('Step 3: Final question generation is running...')
    time.sleep(2)

    # Step 4: Answer generation
    messages.append('Step 4: Answer generation is running...')
    time.sleep(2)
    final_answer = "This is the final answer generated by AI."
    messages.append(f'Here is your answer: {final_answer}')

    return JsonResponse({'messages': messages})